// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPerspective struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Perspective struct {
	ID   string `json:"id"`
	Text string `json:"text"`
}
